### list geoobjects
GET http://localhost:3017/geoinfo/v1/geobject

### get near objects
GET http://localhost:3017/geoinfo/v1/geobject/near?lat=1&lon=2&maxDistance=30

### create geobject
POST http://localhost:3017/geoinfo/v1/geobject
Content-Type: application/json

{
    "data": {
        "test": "test",
        "numbertest": 123
    },
    "tags": [
        "Building"
    ],
    "loc": {
        "type": "Point",
        "coordinates": [
            -73.88,
            40.78
        ]
    }
}

### delete geobject
DELETE http://localhost:3017/geoinfo/v1/geobject/587dae158ab7c0cd6e487c18

### get geobject
GET http://localhost:3017/geoinfo/v1/geobject/58da5b4f750503a87dda328f
